.MACRO INITSTACK 
LDI R20,HIGH(RAMEND) 
OUT SPH,R20 
LDI R20,LOW(RAMEND) 
OUT SPL,R20 
.ENDMACRO 
 
INITSTACK 
CBI DDRC,5 ; PORTC.5=INPUT 
SBI DDRB,5 ; PORTB.5=OUTPUT 
HERE: IN R16,PINC 
  OUT PORTB,R16 
  RJMP HERE  
